### ISSUE TITLE
Undefined Behaviour opposing stat-lowering move use

### ISSUE THREAD

**Issue by Thanat0sNihil** [Thanat0sNihil/pokecrystal#4]
some kind of memory error happening when opposing pokemon use stat lowering moves on you in battle. sometimes manifesting as small visual bugs or audio glitching, sometimes causing hard crashes

**Comment by Thanat0sNihil** [comment]
issue probably lives in the engine/battle/core.asm or effect_commands.asm. 
https://github.com/Thanat0sNihil/pk_crystal/commits/master/engine/battle/effect_commands.asm
https://github.com/Thanat0sNihil/pk_crystal/commits/master/engine/battle/core.asm



@weburdic

**Comment by weburdic** [comment]
Have you tried rolling back to see witch commit introduced this bug?

**Comment by Thanat0sNihil** [comment]
seems like this is the cursed commmit: https://github.com/Thanat0sNihil/pk_crystal/commit/494489426089a8b0b59c0234e55a604b85244c00

**Comment by willSmallHD** [comment]
My first through is an offset issue caused by removing that large chunk of code, but I feel that most of those would be caught by the compiler. You could try adding the routine back and keeping the calls removed to test that.

**Comment by willSmallHD** [comment]
The other likely option would be that the code expects either this routine or the, now uncalled, boost stats routine to organise registers in a specific way that is no longer happening.

**Comment by Thanat0sNihil** [comment]
the answer appears to have been close to your second guess: line 4801 in effect_commands.asm `call BattleCore` without a preceding call arranging the registers seems to have been the source of the problem. fixed in https://github.com/Thanat0sNihil/pk_crystal/commit/d6ff0cbbbbd56ce685135303235a2ba868ec8892
